version: "2"
run:
  tests: true
linters:
  enable:
    - goconst
    - gosec
    - misspell
    - revive
  settings:
    goconst:
      min-len: 3
      min-occurrences: 3
    misspell:
      locale: US
    revive:
      severity: warning
      rules:
        - name: indent-error-flow
        - name: unexported-return
          disabled: true
        - name: var-naming
          disabled: true
  exclusions:
    generated: lax
    rules:
      - linters:
          - errcheck
          - gosec
        path: _test.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - gci
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
